axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 0  # Left thumb stick horizontal
# scale_angular: 0.4
scale_angular: 1.2

enable_button: 8  # L2 shoulder button
enable_turbo_button: 10  # L1 shoulder button
